DROP TABLE IF EXISTS ORDER_LINE;
DROP TABLE IF EXISTS GTORDER;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CUSTOMER_SINCE DATE NOT NULL
);

CREATE TABLE PRODUCT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    IN_STOCK BOOLEAN NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE COMMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TEXT VARCHAR(1000) NOT NULL,
    PRODUCT_ID INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

CREATE TABLE GTORDER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    ORDER_DATE TIMESTAMP NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE ORDER_LINE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT,
    PRODUCT_ID INT,
    AMOUNT INT NOT NULL,
    PURCHASE_PRICE DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES GTORDER(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);


