DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    IN_STOCK BOOLEAN NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE COMMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TEXT VARCHAR(1000) NOT NULL,
    PRODUCT_ID INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);
